name: 美化
on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 10 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4

      - name: 运行脚本
        run: python py/meihua.py

      - name: 提交文件
        run: |
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          git add .
          git commit -m "json格式美化|Unicode自动转换" -a
          git commit -m "Add new JSON files" || echo "No changes to commit"
          git push --force
          
      - name: Telegram通知
        run: |
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=书源格式美化完成!分支：${{ github.ref }}"
